### ISSUE TITLE
투자 단계 기준이 정확하지않아 Stage 테이블 변경 필요

### ISSUE THREAD

**Issue by yoo2wo** [Unicorn-Finder/UnicornFinder#7]
## 목적
> 투자 라운드를 정하는 기준이 명확하지않아 Stage 테이블을 변경해야한다.
## 작업 상세 내용
- [ ] Stage 테이블 삭제
- [ ] 테이블로 하는 대신 ENUM으로 투자라운드 명시
## 참고 사항
[투자 라운드 기준](https://otrade.co/cs/openinsight/view?seq=356)
[표준화 필요한 시리즈ABC](https://www.thebell.co.kr/free/content/ArticleView.asp?key=202104012122449200101021&lcode=00)

**Comment by Goun96** [comment]
Stage테이블 삭제 동의
